sudo: required
language: ruby
cache: bundler
addons:
  postgresql: '9.6'
rvm:
- 2.6.3
before_install:
- gem install bundler:1.17.1
before_script:
- cp config/database.yml{.sample,}
- bundle exec rake db:create db:test:prepare
- yarn install
