sudo: required
language: ruby
cache: bundler
addons:
  postgresql: '9.6'
rvm:
- 2.7.0
before_install:
- gem install bundler:2.1.4
before_script:
- cp config/database.yml{.sample,}
- bundle exec rake db:create db:test:prepare
- yarn install
