version: '3.2'
services:
  test:
    build:
      context: .
      dockerfile: ops/test/Dockerfile
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: bundle
        target: /bundle
        volume:
           nocopy: true
    depends_on:
      - redis
      - db
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:3.0.5
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data
  bundle:
    image: busybox
    volumes:
      - /bundle
volumes:
  redis:
  postgres:
  bundle:
  src:
