refresh_btc_txs:
  cron: "*/10 * * * * *"
  class: "CheckTxsJob"
  queue: "btc"
  args:
    - btc

sync_unconfirmed_btc_txs:
  cron: "*/5 * * * * *"
  class: "SyncUnconfirmedTxsJob"
  queue: "btc"
  args:
    - "btc"

sync_btc_missing_blocks:
  cron: "0 0 * * *"
  class: "SyncMissingBlocksJob"
  queue: "btc"
  args:
    - "btc"